/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.gob.oefa.planefa.programacionsancionadora2.view;

import pe.gob.oefa.planefa.evaluacionabiental.view.frmProgramacionEvaluacionesAmbientales;
import pe.gob.oefa.planefa.programacionsancionadora1.view.frmProgramacionSancionadora1;

/**
 *
 * @author Daniel
 */
public class frmProgramacionSancionadora2 extends javax.swing.JFrame {

    /**
     * Creates new form JFDatosGenerales
     */
    public frmProgramacionSancionadora2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbSupervision = new javax.swing.JRadioButton();
        rbDatosGenerales = new javax.swing.JRadioButton();
        rbEvaluacionesAmbientales = new javax.swing.JRadioButton();
        rbSancionadora1 = new javax.swing.JRadioButton();
        rbSancionadora2 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActividades = new javax.swing.JTable();
        lblProgramacionPass = new javax.swing.JLabel();
        cbmNuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbmSiguiente = new javax.swing.JButton();
        cbmAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setBackground(new java.awt.Color(240, 240, 204));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Plan anual de actividades 2020 (MUNICIPALIDAD PROVINCIAL 1 - 22012)");
        lblTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbSupervision.setForeground(new java.awt.Color(102, 102, 102));
        rbSupervision.setText("Programación de la supervisión");
        rbSupervision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSupervisionActionPerformed(evt);
            }
        });

        rbDatosGenerales.setForeground(new java.awt.Color(102, 102, 102));
        rbDatosGenerales.setText("Datos General");
        rbDatosGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDatosGeneralesActionPerformed(evt);
            }
        });

        rbEvaluacionesAmbientales.setForeground(new java.awt.Color(102, 102, 102));
        rbEvaluacionesAmbientales.setText("Programación de evaluaciones ambientales");
        rbEvaluacionesAmbientales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEvaluacionesAmbientalesActionPerformed(evt);
            }
        });

        rbSancionadora1.setForeground(new java.awt.Color(102, 102, 102));
        rbSancionadora1.setText("Programación del ejercicio de la potestad sancionadora l");
        rbSancionadora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSancionadora1ActionPerformed(evt);
            }
        });

        rbSancionadora2.setForeground(new java.awt.Color(0, 204, 51));
        rbSancionadora2.setSelected(true);
        rbSancionadora2.setText("Programación del ejercicio de la potestad sancionadora ll");
        rbSancionadora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSancionadora2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbDatosGenerales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSupervision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSancionadora1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSancionadora2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbEvaluacionesAmbientales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEvaluacionesAmbientales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSancionadora1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSupervision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbDatosGenerales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSancionadora2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblActividades.setBackground(new java.awt.Color(204, 204, 204));
        tblActividades.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblActividades.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tblActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Emisión de resoluciones finales de primera instancia de procedimientos iniciados el año anterior a la ejecución del planefa ", "NINGUNO", "Expediente concluido", "1", "1", "1", "1", "0", "0", "0", "0", "0", "0", "0", "0", "4", "3,000.00"},
                {"2", "Emisión de resoluciones finales de primera instancia de procedimientos iniciados dos años antes de la ejecución del planefa", "NINGUNO", "Expediente concluido", "2", "2", "4", "0", "0", "0", "0", "0", "0", "0", "0", "0", "8", "30,000.00"},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "", "", ""},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "Actividad Operativa(**)", "Sector(***)", "Unidad de Medida", "Ene", "Feb", "Mar", "Abril", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic", "Meta Fisica Anual", "Presupuesto Anual (S/.)"
            }
        ));
        jScrollPane1.setViewportView(tblActividades);

        lblProgramacionPass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProgramacionPass.setText("Programación de PAS que se proyecta tramitar en el año (*) ");

        cbmNuevo.setText("+ NUEVO");
        cbmNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(lblProgramacionPass)
                .addGap(18, 18, 18)
                .addComponent(cbmNuevo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgramacionPass, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmNuevo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbmSiguiente.setText("SIGUIENTE");
        cbmSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmSiguienteActionPerformed(evt);
            }
        });

        cbmAnterior.setText("ANTERIOR");
        cbmAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbmAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmSiguiente)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmSiguiente)
                    .addComponent(cbmAnterior))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSupervisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSupervisionActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_rbSupervisionActionPerformed

    private void rbDatosGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDatosGeneralesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDatosGeneralesActionPerformed

    private void rbEvaluacionesAmbientalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEvaluacionesAmbientalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEvaluacionesAmbientalesActionPerformed

    private void rbSancionadora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSancionadora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSancionadora1ActionPerformed

    private void rbSancionadora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSancionadora2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSancionadora2ActionPerformed

    private void cbmNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmNuevoActionPerformed
        frmProgramacionSancionadora2Editar abrir = new frmProgramacionSancionadora2Editar();
        abrir.setVisible(true);
    }//GEN-LAST:event_cbmNuevoActionPerformed

    private void cbmSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmSiguienteActionPerformed
        frmProgramacionEvaluacionesAmbientales abrir = new frmProgramacionEvaluacionesAmbientales();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cbmSiguienteActionPerformed

    private void cbmAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmAnteriorActionPerformed
        frmProgramacionSancionadora1 abrir = new frmProgramacionSancionadora1();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cbmAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProgramacionSancionadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProgramacionSancionadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProgramacionSancionadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProgramacionSancionadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProgramacionSancionadora2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbmAnterior;
    private javax.swing.JButton cbmNuevo;
    private javax.swing.JButton cbmSiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProgramacionPass;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbDatosGenerales;
    private javax.swing.JRadioButton rbEvaluacionesAmbientales;
    private javax.swing.JRadioButton rbSancionadora1;
    private javax.swing.JRadioButton rbSancionadora2;
    private javax.swing.JRadioButton rbSupervision;
    private javax.swing.JTable tblActividades;
    // End of variables declaration//GEN-END:variables
}
