/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.gob.oefa.planefa.datosgenerales.view;

import pe.gob.oefa.planefa.programacionsupervision.view.frmProgramacionSupervision;
import View.PlanefaSingleton;
import java.util.Date;
import pe.gob.oefa.planefa.bo.catalogo.Ambito;
import pe.gob.oefa.planefa.bo.catalogo.ClasificacionMef;
import pe.gob.oefa.planefa.bo.catalogo.Efa;
import pe.gob.oefa.planefa.bo.catalogo.OficinaDesconcentrada;
import pe.gob.oefa.planefa.bo.catalogo.TipoGobierno;
import pe.gob.oefa.planefa.bo.catalogo.Ubigeo;
import pe.gob.oefa.planefa.bo.planefa.Periodo;
import pe.gob.oefa.planefa.bo.planefa.Planefa;

/**
 *
 * @author Daniel
 */
public class frmDatosGenerales extends javax.swing.JFrame {

    private Planefa planefa;
    public frmDatosGenerales() {
        initComponents();
        this.planefa = PlanefaSingleton.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbSupervision = new javax.swing.JRadioButton();
        rbDatosGenerales = new javax.swing.JRadioButton();
        rbAmbientales = new javax.swing.JRadioButton();
        rbPotestadSancionadora1 = new javax.swing.JRadioButton();
        rbSancionadora2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        lblDatosGenerales = new javax.swing.JLabel();
        lblNombreEfa = new javax.swing.JLabel();
        txtNombreEfa = new javax.swing.JTextField();
        lblAnioPlanefa = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        lblTipoEfa = new javax.swing.JLabel();
        cmbTipoEfa = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblDatosIngresar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatosIngresar = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        lblLineamientos = new javax.swing.JLabel();
        lblLink = new javax.swing.JLabel();
        lblAnexoPlanefa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setBackground(new java.awt.Color(240, 240, 204));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Plan anual de actividades 2020 (MUNICIPALIDAD PROVINCIAL 1 - 22012)");
        lblTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbSupervision.setForeground(new java.awt.Color(102, 102, 102));
        rbSupervision.setText("Programación de la supervisión");
        rbSupervision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSupervisionActionPerformed(evt);
            }
        });

        rbDatosGenerales.setForeground(new java.awt.Color(0, 204, 51));
        rbDatosGenerales.setSelected(true);
        rbDatosGenerales.setText("Datos General");
        rbDatosGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDatosGeneralesActionPerformed(evt);
            }
        });

        rbAmbientales.setForeground(new java.awt.Color(102, 102, 102));
        rbAmbientales.setText("Programación de evaluaciones ambientales");
        rbAmbientales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAmbientalesActionPerformed(evt);
            }
        });

        rbPotestadSancionadora1.setForeground(new java.awt.Color(102, 102, 102));
        rbPotestadSancionadora1.setText("Programación del ejercicio de la potestad sancionadora l");
        rbPotestadSancionadora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPotestadSancionadora1ActionPerformed(evt);
            }
        });

        rbSancionadora2.setForeground(new java.awt.Color(102, 102, 102));
        rbSancionadora2.setText("Programación del ejercicio de la potestad sancionadora ll");
        rbSancionadora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSancionadora2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbDatosGenerales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSupervision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPotestadSancionadora1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSancionadora2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbAmbientales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAmbientales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbPotestadSancionadora1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSupervision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbDatosGenerales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSancionadora2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDatosGenerales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDatosGenerales.setText("Datos Generales");

        lblNombreEfa.setText("Nombre de la EFA *");

        txtNombreEfa.setText("22012 - MUNICIPALIDAD PROVINCIAL 1");

        lblAnioPlanefa.setText("Año del PLANEFA *");

        txtAnio.setText("2020");

        lblTipoEfa.setText("Tipo de EFA *");

        cmbTipoEfa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOCAL" }));
        cmbTipoEfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoEfaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatosGenerales)
                    .addComponent(lblNombreEfa)
                    .addComponent(txtNombreEfa, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnioPlanefa)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoEfa)
                    .addComponent(cmbTipoEfa, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosGenerales)
                .addGap(18, 18, 18)
                .addComponent(lblNombreEfa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreEfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblAnioPlanefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoEfa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipoEfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDatosIngresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDatosIngresar.setText("Guia de datos a ingresar");

        txtDatosIngresar.setColumns(20);
        txtDatosIngresar.setRows(5);
        txtDatosIngresar.setText("*I  Programación de supervisiones\n\n*II Programación del ejercicio de la potestad sancionadora\n  +a.Programación del ejercicio de la potestad\n     sancionadora I.\n  +b.Programación del ejercicio de la potestad\n     sancionadora II.\n\n*III Programación de evaluaciones ambientales\n\n*IV  Plan de instrumentos normativos\n  +a.Plan de instrumentos normativos I\n  +b.Plan de instrumentos normativos II\n");
        txtDatosIngresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtDatosIngresar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblDatosIngresar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLineamientos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLineamientos.setText("Lineamientos");

        lblLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLink.setForeground(new java.awt.Color(0, 0, 255));
        lblLink.setText("Resolución N° 004-2010 - DEFACO-EL-PERUANO");

        lblAnexoPlanefa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAnexoPlanefa.setForeground(new java.awt.Color(0, 0, 255));
        lblAnexoPlanefa.setText("* Anexo - PLANEFA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLineamientos)
                    .addComponent(lblLink)
                    .addComponent(lblAnexoPlanefa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLineamientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLink)
                .addGap(18, 18, 18)
                .addComponent(lblAnexoPlanefa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSiguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSupervisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSupervisionActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_rbSupervisionActionPerformed

    private void rbDatosGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDatosGeneralesActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_rbDatosGeneralesActionPerformed

    private void rbAmbientalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAmbientalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAmbientalesActionPerformed

    private void rbPotestadSancionadora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPotestadSancionadora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPotestadSancionadora1ActionPerformed

    private void rbSancionadora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSancionadora2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSancionadora2ActionPerformed

    private void cmbTipoEfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoEfaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoEfaActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        //Periodo
        Periodo periodo = new Periodo(Integer.parseInt(this.txtAnio.getText()), new Date(), new Date());        
        
        //Datos de la EFA
        Ubigeo ubigeo = new  Ubigeo();
        Ambito ambito = new Ambito("1100", "Nacional");//Regional//Local
        TipoGobierno tipoGobierno = new TipoGobierno("1200", "Distrital");//Distrital, Provincial, Centro poblado
        ClasificacionMef clasificacionMef = new ClasificacionMef("1300", "A");
        OficinaDesconcentrada oficinaDesconcentrada = new OficinaDesconcentrada("2000", "OD x");                
        Efa efa = new Efa("1000", "20425856214", "Municipalidad Distrital de Surco", ubigeo, ambito, tipoGobierno, clasificacionMef, oficinaDesconcentrada);
          
      this.planefa.setEfa(efa);
      this.planefa.setPeriodo(periodo);
      
      frmProgramacionSupervision abrirProgramacionsupervision =  new frmProgramacionSupervision();
      abrirProgramacionsupervision.setVisible(true);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDatosGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDatosGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDatosGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDatosGenerales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDatosGenerales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cmbTipoEfa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnexoPlanefa;
    private javax.swing.JLabel lblAnioPlanefa;
    private javax.swing.JLabel lblDatosGenerales;
    private javax.swing.JLabel lblDatosIngresar;
    private javax.swing.JLabel lblLineamientos;
    private javax.swing.JLabel lblLink;
    private javax.swing.JLabel lblNombreEfa;
    private javax.swing.JLabel lblTipoEfa;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbAmbientales;
    private javax.swing.JRadioButton rbDatosGenerales;
    private javax.swing.JRadioButton rbPotestadSancionadora1;
    private javax.swing.JRadioButton rbSancionadora2;
    private javax.swing.JRadioButton rbSupervision;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextArea txtDatosIngresar;
    private javax.swing.JTextField txtNombreEfa;
    // End of variables declaration//GEN-END:variables
}
