/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.gob.oefa.planefa.programacionsupervision.view;


import pe.gob.oefa.planefa.programacionsancionadora1.view.frmProgramacionSancionadora1;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import org.bson.Document;
import pe.gob.oefa.planefa.bo.actividad.Actividad;
import pe.gob.oefa.planefa.bo.actividad.ActividadSupervision;
import pe.gob.oefa.planefa.bo.catalogo.ActividadOperativa;
import pe.gob.oefa.planefa.bo.catalogo.ObjetoSupervision;
import pe.gob.oefa.planefa.bo.catalogo.Sector;
import pe.gob.oefa.planefa.bo.catalogo.UnidadMedida;
import pe.gob.oefa.planefa.bo.planefa.Planefa;
import pe.gob.oefa.planefa.programacionsupervision.model.SupervisionTableModel;
import pe.gob.oefa.planefa.resources.PlanefaSingleton;

/**
 *
 * @author Daniel
 */
public class frmProgramacionSupervision extends javax.swing.JFrame {

    private Planefa planefa;
    private SupervisionTableModel supervisionTableModel; 
    private ActividadSupervision actividadSeleccionada;
    private SeccionPlanefa seccion = SeccionPlanefa.DATOS_GENERALES;
    
    public frmProgramacionSupervision() {
        initComponents();
        this.planefa = PlanefaSingleton.getInstance();
        this.mostrarTabla();
    }
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbSupervision = new javax.swing.JRadioButton();
        rbDatosGenerales = new javax.swing.JRadioButton();
        rbEvaluacionesAmbientales = new javax.swing.JRadioButton();
        rbSancionadora1 = new javax.swing.JRadioButton();
        rbSancionadora2 = new javax.swing.JRadioButton();
        panelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActividades = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(240, 240, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Plan anual de actividades 2020 (MUNICIPALIDAD PROVINCIAL 1 - 22012)");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbSupervision.setForeground(new java.awt.Color(0, 204, 51));
        rbSupervision.setSelected(true);
        rbSupervision.setText("Programación de la supervisión");
        rbSupervision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSupervisionActionPerformed(evt);
            }
        });

        rbDatosGenerales.setForeground(new java.awt.Color(102, 102, 102));
        rbDatosGenerales.setText("Datos General");
        rbDatosGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDatosGeneralesActionPerformed(evt);
            }
        });

        rbEvaluacionesAmbientales.setForeground(new java.awt.Color(102, 102, 102));
        rbEvaluacionesAmbientales.setText("Programación de evaluaciones ambientales");
        rbEvaluacionesAmbientales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEvaluacionesAmbientalesActionPerformed(evt);
            }
        });

        rbSancionadora1.setForeground(new java.awt.Color(102, 102, 102));
        rbSancionadora1.setText("Programación del ejercicio de la potestad sancionadora l");
        rbSancionadora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSancionadora1ActionPerformed(evt);
            }
        });

        rbSancionadora2.setForeground(new java.awt.Color(102, 102, 102));
        rbSancionadora2.setText("Programación del ejercicio de la potestad sancionadora ll");
        rbSancionadora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSancionadora2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbDatosGenerales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSupervision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSancionadora1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSancionadora2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbEvaluacionesAmbientales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEvaluacionesAmbientales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSancionadora1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSupervision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbDatosGenerales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSancionadora2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblActividades.setBackground(new java.awt.Color(204, 204, 204));
        tblActividades.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblActividades.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tblActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "SUPERVISIÓN", "NINGUNO", "RUIDO", "INFORME DE SUPERVISIÓN", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "0", "0", "20", "4,000.00"},
                {"2", "SUPERVISIÓN", "NINGUNO", "EMISIONES", "INFORME DE SUPERVISIÓN", "0", "1", "0", "2", "0", "0", "0", "1", "2", "0", "0", "0", "6", "2,000.00"},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Totales :", "26", "6,000.00"},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "Actividad Operativa", "Sector", "Objeto de Supervisión", "Unidad de Medida", "Ene", "Feb", "Mar", "Abril", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic", "Meta Fisica Anual", "Presupuesto Anual (S/.)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblActividadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblActividades);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo.setText("Programación de supervisiones (*) ");

        btnNuevo.setText("Agregar actividad");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNuevo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setText("ANTERIOR");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSupervisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSupervisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSupervisionActionPerformed

    private void rbDatosGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDatosGeneralesActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_rbDatosGeneralesActionPerformed

    private void rbEvaluacionesAmbientalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEvaluacionesAmbientalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEvaluacionesAmbientalesActionPerformed

    private void rbSancionadora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSancionadora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSancionadora1ActionPerformed

    private void rbSancionadora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSancionadora2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSancionadora2ActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        
        JFrame childFrame = new frmProgramacionSupervisionEditar(null, this); //Creo una instancia de mi otra ventana "childFrame"
        childFrame.setLocationRelativeTo(null); //Que cuando aparezca la ventana sea en el centro de la pantalla principal
        childFrame.setResizable(false); //Que no se pueda cambiar el tamaño
        childFrame.setVisible(true); //Que sea visible            
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        irPasoSiguiente();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void tblActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblActividadesMouseClicked
        
        //Muestra la fila seleccionada para el evento MouseClicked
        System.out.println("Row selected:"+ this.tblActividades.getSelectedRow());
        //Obtiene el indice de la fila seleccionada
        int selectedRow = this.tblActividades.getSelectedRow(); 
        //Obtiene la Activida desde la  programación sgún el indice de la fila seleccionada
        this.actividadSeleccionada = (ActividadSupervision)planefa.getActividadesSupervision().getProgramacion().get(selectedRow);
        
        //Abre el formulario de edición
        JFrame childFrame = new frmProgramacionSupervisionEditar(actividadSeleccionada, this); //Creo una instancia de mi otra ventana "childFrame"
        childFrame.setLocationRelativeTo(null); //Que cuando aparezca la ventana sea en el centro de la pantalla principal
        childFrame.setResizable(false); //Que no se pueda cambiar el tamaño        
        childFrame.setVisible(true); //Que sea visible
    }//GEN-LAST:event_tblActividadesMouseClicked

    
    public void mostrarTabla(){
        try {        
            //List<Actividad> programacion = planefa.getActividadesSupervision().getProgramacion();                        
            supervisionTableModel = new SupervisionTableModel(planefa);
            this.tblActividades.setModel(supervisionTableModel);
            //this.tblActividades2.setAutoCreateRowSorter(true);
        } catch (Exception e) {
            e.printStackTrace();
        }   
    }
    
    public void mostrarSeccionDatosGenerales(){
        
    }
    
    public void mostrarSeccionSupervision(){
        
    }
    
    public void mostrarSeccionPAS(){
        
    }
    
    public void mostrarSeccionEvaluacion(){
        
    }
    
    public void mostrarSeccionInstrumentosNormativos(){
        
    }
    
    public void mostrarSeccionResumen(){
        
    }
    
    private void irPasoSiguiente() {
        switch (this.seccion) {
            case DATOS_GENERALES:
                this.seccion = SeccionPlanefa.SUPERVISIONES;
                mostrarSeccionSupervision();
                break;
            case SUPERVISIONES:
                this.seccion = SeccionPlanefa.PAS;
                mostrarSeccionPAS();
                break;
            case PAS:
                this.seccion = SeccionPlanefa.EVALUACIONES;
                mostrarSeccionEvaluacion();
                break;
            case EVALUACIONES:
                this.seccion = SeccionPlanefa.INSTRUMENTOS_NORMATIVOS;
                mostrarSeccionInstrumentosNormativos();
                break;
            case INSTRUMENTOS_NORMATIVOS:
                this.seccion = SeccionPlanefa.RESUMEN;
                mostrarSeccionResumen();
                break;
            default:
                this.seccion = SeccionPlanefa.DATOS_GENERALES;
                mostrarSeccionDatosGenerales();
        }
    }
    
    private void irPasoAnterior() {
        switch (this.seccion) {
            case DATOS_GENERALES:
                this.seccion = SeccionPlanefa.SUPERVISIONES;
                break;
            case SUPERVISIONES:
                this.seccion = SeccionPlanefa.PAS;
                break;
            case PAS:
                this.seccion = SeccionPlanefa.EVALUACIONES;
                break;
            case EVALUACIONES:
                this.seccion = SeccionPlanefa.INSTRUMENTOS_NORMATIVOS;
                break;
            case INSTRUMENTOS_NORMATIVOS:
                this.seccion = SeccionPlanefa.RESUMEN;
                break;
            default:
                this.seccion = SeccionPlanefa.DATOS_GENERALES;
        }
    }
    
    public static void main(String args[]) {    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProgramacionSupervision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton rbDatosGenerales;
    private javax.swing.JRadioButton rbEvaluacionesAmbientales;
    private javax.swing.JRadioButton rbSancionadora1;
    private javax.swing.JRadioButton rbSancionadora2;
    private javax.swing.JRadioButton rbSupervision;
    private javax.swing.JTable tblActividades;
    // End of variables declaration//GEN-END:variables
}
